# zip genomes before running Snakefile under ~/AL_onemetagenome/containment$
# sourmash sig cat *.sig -o genomes.zip
SAMPLES, = glob_wildcards('/home/zyzhao/AL_onemetagenome/assemblies/{metagenome}.megahit.fa.gz.sig')
print(SAMPLES)

rule all:
    input:
        expand("{metagenome}.x.genomes.prefetch.csv", metagenome=SAMPLES),

rule prefetch:
    input:
        gzip="/home/zyzhao/AL_onemetagenome/containment/genomes.zip",
        megahit_sig="/home/zyzhao/AL_onemetagenome/assemblies/{metagenome}.megahit.fa.gz.sig"
    output:
        pref="{metagenome}.x.genomes.prefetch.csv",

    conda: "env-sourmash.yml"
    shell: """
        sourmash prefetch {input.megahit_sig} {input.gzip} -o {output.pref} --threshold=0
    """
