SAMPLES, = glob_wildcards('/home/zyzhao/assloss/assemblies/env8/{sample}.megahit.fa.gz.sig')
print(SAMPLES)

rule all:
    input:
        expand("{sample}.x.genomes.prefetch.csv", sample=SAMPLES),

rule prefetch:
    input:
        gzip="/home/zyzhao/assloss/containment/env8/gprefetch/genomes.zip",
        megahit_sig="/home/zyzhao/assloss/assemblies/env8/{sample}.megahit.fa.gz.sig"
    output:
        pref="{sample}.x.genomes.prefetch.csv",

    conda: "env-sourmash.yml"
    threads: 1
    shell: """
        sourmash prefetch {input.megahit_sig} {input.gzip} -o {output.pref} --threshold=0
    """
