SAMPLES, = glob_wildcards('/home/zyzhao/assloss/grist/env8/outputs.env8_samples/genomes/{sample}.sig')
print(SAMPLES)

rule all:
    input:
        expand("{sample}.x.ERR257713.containment.csv", sample=SAMPLES),
        expand("{sample}.x.ERR257714.containment.csv", sample=SAMPLES),
        expand("{sample}.x.ERR257715.containment.csv", sample=SAMPLES),
        expand("{sample}.x.ERR257716.containment.csv", sample=SAMPLES),
        expand("{sample}.x.ERR272375.containment.csv", sample=SAMPLES),
        expand("{sample}.x.ERR272377.containment.csv", sample=SAMPLES),
        expand("{sample}.x.ERR272376.containment.csv", sample=SAMPLES),
        expand("{sample}.x.ERR272378.containment.csv", sample=SAMPLES),

rule calc_containment:
    input:
        genome_sig="/home/zyzhao/assloss/grist/env8/outputs.env8_samples/genomes/{sample}.sig",
        megahit_sig="/home/zyzhao/assloss/assemblies/env8/{metagenome}.megahit.fa.gz.sig"

    output:
        p_containment= "{sample}.x.{metagenome}.containment.csv",
#        dir = directory("{sample}.p_megahit.d"),
    conda: "env-sourmash.yml"
    threads: 1
    # sourmash uses single threads
    shell: """
        sourmash search --containment {input.genome_sig} {input.megahit_sig} -o {output.p_containment}
    """
