SAMPLES, = glob_wildcards('/home/zyzhao/AL_onemetagenome/grist/outputs.1env_sample/genomes/{sample}_genomic.fna.gz')
print(SAMPLES)

rule all:
    input:
        expand("{sample}.x.ERR257715.containment.csv", sample=SAMPLES),

rule genome_sketch:
    input:
        "/home/zyzhao/AL_onemetagenome/grist/outputs.1env_sample/genomes/{sample}_genomic.fna.gz",
    output:
        genome_sketch= "{sample}.sig",
#        dir = directory("{sample}.sig.d"),
    conda: "env-sourmash.yml"
    shell: """
        sourmash sketch dna {input} -o {output.genome_sketch}
    """

rule calc_containment:
    input:
        genome_sig="{sample}.sig",
        megahit_sig="/home/zyzhao/AL_onemetagenome/assemblies/{metagenome}.megahit.fa.gz.sig"

    output:
        p_containment= "{sample}.x.{metagenome}.containment.csv",
#        dir = directory("{sample}.p_megahit.d"),
    conda: "env-sourmash.yml"
    threads: 1
    # sourmash uses single threads
    shell: """
        sourmash search --containment {input.genome_sig} {input.megahit_sig} -o {output.p_containment}
    """
