PAIRS, = glob_wildcards('/home/zyzhao/AL_onemetagenome/grist/outputs.1env_sample/mapping/{pair}.mapped.fq.gz')
# then PAIRS would be [ "ERRXYZ.x.genomeABC", "ERRXYZ.x.genomeDEF"]

# SAMPLES, = glob_wildcards('/home/zyzhao/assloss/grist/env8/outputs.env8_samples/mapping/{metagenome}.x.{genome}.1.mapped.fq.gz')
print(PAIRS)

rule all:
    input:
#        expand("{pair}.reads.x.assembly.bam", pair=PAIRS),
#        expand("{pair}.diff.fq.gz", pair=PAIRS),
#        expand("{metagenome}.x.{sample}.diff.fq", sample=SAMPLES),
#        expand("{pair}.diff.reads.x.genome.bam", pair=PAIRS),
#        expand("{pair}.diff.reads.x.genome.sort.bam.bai", pair=PAIRS),
        expand("{pair}.diff.csv", pair=PAIRS),
        expand("{pair}.all.csv", pair=PAIRS),
        expand("{pair}.diff2.csv", pair=PAIRS),

rule mapped_assembly:
    input:
        mapped_reads="/home/zyzhao/AL_onemetagenome/grist/outputs.1env_sample/mapping/{metagenome}.x.{genome}.mapped.fq.gz",

    output:
        mapped_assembly= "{metagenome}.x.{genome}.mapped.assembly.fa",
        dir = directory("{metagenome}.x.{genome}.p_megahit.d"),

    conda: "env-diff.yml"
    threads: 32
    # sourmash uses single threads
    shell: """
        megahit -f -t {threads} -r {input.mapped_reads} -o {output.dir}
        cp {output.dir}/final.contigs.fa {output.mapped_assembly}
    """
    
rule minimap:
    input:
        mapped_assembly= "{metagenome}.x.{genome}.mapped.assembly.fa",
        mapped_reads="/home/zyzhao/AL_onemetagenome/grist/outputs.1env_sample/mapping/{metagenome}.x.{genome}.mapped.fq.gz",
        
    output:
        minimap= "{metagenome}.x.{genome}.reads.x.assembly.bam",
        
    conda: "env-diff.yml"
    threads: 1
    shell: """
        minimap2 -ax sr -t 32 {input.mapped_assembly} {input.mapped_reads} | samtools view -b -F 4 - | samtools sort - > {output.minimap}
    """
rule samtool:
    input:
        bamfile= "{metagenome}.x.{genome}.reads.x.assembly.bam",
        
    output:
        samfile= "{metagenome}.x.{genome}.reads.x.assembly.fq.gz",
        
    conda: "env-diff.yml"
    threads: 1
    shell: """
        samtools bam2fq {input.bamfile} | gzip -9c > {output.samfile}
    """    
    
rule diff_output:
    input:
        mapped_reads="/home/zyzhao/AL_onemetagenome/grist/outputs.1env_sample/mapping/{metagenome}.x.{genome}.mapped.fq.gz",
        samfile= "{metagenome}.x.{genome}.reads.x.assembly.fq.gz",
        
    output:
        diff= "{metagenome}.x.{genome}.diff.fq.gz",
    
    conda: "env-diff.yml"    
    threads: 1
    shell: """
        ./output-diff-reads.py {input.mapped_reads} {input.samfile} -o {output.diff}
        gzip {output.diff}
    """

rule diff_map:
    input:
        diff= "{metagenome}.x.{genome}.diff.fq.gz",
        mapped_genome="/home/zyzhao/AL_onemetagenome/grist/outputs.1env_sample/genomes/{genome}_genomic.fna.gz",
        
    output:
        minimap= "{metagenome}.x.{genome}.diff.reads.x.genome.bam",
        
    conda: "env-diff.yml"
    threads: 32
    shell: """
        minimap2 -ax sr -t {threads} {input.mapped_genome} {input.diff} | samtools view -b -F 4 - | samtools sort - > {output.minimap}
    """

rule sort:
    input:
        bamfile= "{filename}.bam",
    output:
        sortfile= "{filename}.sort.bam",

    conda: "env-diff.yml"
    threads: 1
    shell: """
        samtools sort {input.bamfile} -o {output.sortfile}
    """

rule index:
    input:
        sortfile= "{filename}.sort.bam",
    output:
        indexfile= "{filename}.sort.bam.bai",

    conda: "env-diff.yml"
    threads: 1
    shell: """
        samtools index {input.sortfile}
    """
# bam1: contain all reads mapped to a genome
# bam2: contain reads that did not mapped to the assembly
# csv will output the coverage of read that mapped to the genome but did not end up in the assembly
rule diff_csv:
    input:
        bam1= "/home/zyzhao/AL_onemetagenome/grist/outputs.1env_sample/mapping/{metagenome}.x.{genome}.sort.bam",
        bam2= "/home/zyzhao/AL_onemetagenome/subtract/{metagenome}.x.{genome}.diff.reads.x.genome.sort.bam",
        bai1= "/home/zyzhao/AL_onemetagenome/grist/outputs.1env_sample/mapping/{metagenome}.x.{genome}.sort.bam.bai",
        bai2= "/home/zyzhao/AL_onemetagenome/subtract/{metagenome}.x.{genome}.diff.reads.x.genome.sort.bam.bai",
    output:
        csvfile= "{metagenome}.x.{genome}.diff.csv",
    conda: "env-diff.yml"
    threads: 1
    shell: """
    ./calc-coverage-diff-sam-bam.py {input.bam1} {input.bam2} -o {output.csvfile}
    """
# New script cal:
rule diff2_csv:
    input:
        bam1= "/home/zyzhao/AL_onemetagenome/grist/outputs.1env_sample/mapping/{metagenome}.x.{genome}.bam.depth",
        bam2= "/home/zyzhao/AL_onemetagenome/subtract/{metagenome}.x.{genome}.diff.reads.x.genome.sort.bam",
        bai2= "/home/zyzhao/AL_onemetagenome/subtract/{metagenome}.x.{genome}.diff.reads.x.genome.sort.bam.bai",
    output:
        csvfile= "{metagenome}.x.{genome}.diff2.csv",
    conda: "env-diff.yml"
    threads: 1
    shell: """
    ./calc-coverage-diff-2.py {input.bam1} {input.bam2} -o {output.csvfile}
    """    
# bam1: contain all reads mapped to a genome
# csv will output the coverage of all read
rule all_csv:
    input:
        bam1= "/home/zyzhao/AL_onemetagenome/grist/outputs.1env_sample/mapping/{metagenome}.x.{genome}.sort.bam",
        bai1= "/home/zyzhao/AL_onemetagenome/grist/outputs.1env_sample/mapping/{metagenome}.x.{genome}.sort.bam.bai",
    output:
        csvfile= "{metagenome}.x.{genome}.all.csv",
    conda: "env-diff.yml"
    threads: 1
    shell: """
    ./calc-coverage-diff-sam-bam.py {input.bam1} {input.bam1} -o {output.csvfile}
    """
